homepage:
    path: /
    controller: App\Controller\WebController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

user_registration:
    path: /registration
    controller: App\Controller\RegistrationController::registration

folder_all:
    path: /folder/all.{_format}
    methods: [GET]
    controller: App\Controller\FoldersController::allFolders
    defaults:
        _format: json

folder_new:
    path: /folder/new.{_format}
    methods: [POST]
    controller: App\Controller\FoldersController::create
    defaults:
        _format: json

